version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload --timeout-keep-alive 2400
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - prod.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - prod.env

volumes:
  postgres_data: